//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInf
    {
        public string check_id { get; set; }
        public string game_id { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
