//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int order_id { get; set; }
        public string users_id { get; set; }
        public System.DateTime order_date { get; set; }
        public int status_id { get; set; }
        public string game_id { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Statuss Statuss { get; set; }
        public virtual Users Users { get; set; }
    }
}
